flyway.url=jdbc:postgresql://postgres:5432/pqt_shop
flyway.user=pqt_admin
flyway.password=${POSTGRES_PASSWORD}
flyway.schemas=public
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=false
flyway.validateOnMigrate=true
