/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pabst' at '27.06.17 10:25' with Gradle 3.2.1
 *
 * @author pabst, @date 27.06.17 10:25
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
