import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'pabst' at '27.06.17 10:25' with Gradle 3.2.1
 *
 * @author pabst, @date 27.06.17 10:25
 */
public class PostgresQueryToolTest {
    @Test public void testSomeLibraryMethod() {
        PostgresQueryTool classUnderTest = new PostgresQueryTool();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
