import org.junit.jupiter.api.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'pabst' at '27.06.17 10:25' with Gradle 3.2.1
 *
 * @author pabst, @date 27.06.17 10:25
 */
public class PostgresQueryToolTest {
    @Test
    public void testSomeLibraryMethod() {

    }
}
